export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const GET_REFRESH_TOKEN = 'GET_REFRESH_TOKEN';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const SIGN_IN = 'SIGN_IN';
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
